# Site settings
title: Rod Dong
email: dongxiao@usc.edu
description: > # keep this and put description below
  Game Programmer and Technical Artist
url: "https://RodDong.com" # the base hostname & protocol for your site
linkedin_url: "https://www.linkedin.com/in/xiaolong-dong-368139220/"
github_username: RodDong
footer_text: "This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

# Build settings
markdown: kramdown
permalink: pretty
